name: tasce_mobile
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.64.0
  collection: ^1.17.2
  onesignal_flutter: ^5.0.4
  http: ^1.1.0
  table_calendar: ^3.0.9
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  js: ^0.6.7
  firebase_auth_platform_interface: ^7.0.9

  # Essential UI packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^13.2.0

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0 # Added this line

  # Network
  dio: ^5.4.1

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.5
  package_info_plus: ^4.2.0

  # UI Components
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4

  # Authentication
  local_auth: ^2.1.8

  # PDF Generation and Printing
  pdf: ^3.10.8
  printing: ^5.11.1
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.8

  # App Icon

  # Splash Screen

flutter:
  uses-material-design: true

  assets:
    - assets/images/oouth_logo.png
    - assets/images/oouth_logo_watermark.png
    - assets/images/ogun_logo.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
