// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCox0IoSmgejaExIOAE8MpfuXQTh50UrRg',
    appId: '1:903805952685:android:fe8d909e92934564109c24',
    messagingSenderId: '903805952685',
    projectId: 'oouth-e2a0e',
    storageBucket: 'oouth-e2a0e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5kWIFpnwukHlPUc-QzO7wpY4G2w0Wn-U',
    appId: '1:903805952685:web:1d0af72c2400bc51109c24',
    messagingSenderId: '903805952685',
    projectId: 'oouth-e2a0e',
    authDomain: 'oouth-e2a0e.firebaseapp.com',
    storageBucket: 'oouth-e2a0e.firebasestorage.app',
    measurementId: 'G-18BWWMYWXP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuxXiK7DruFFg7NwbnlRMUXHFBC-8QbgA',
    appId: '1:903805952685:ios:31d3cdf706b3341c109c24',
    messagingSenderId: '903805952685',
    projectId: 'oouth-e2a0e',
    storageBucket: 'oouth-e2a0e.firebasestorage.app',
    iosBundleId: 'com.example.tasceMobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxXiK7DruFFg7NwbnlRMUXHFBC-8QbgA',
    appId: '1:903805952685:ios:31d3cdf706b3341c109c24',
    messagingSenderId: '903805952685',
    projectId: 'oouth-e2a0e',
    storageBucket: 'oouth-e2a0e.firebasestorage.app',
    iosBundleId: 'com.example.tasceMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5kWIFpnwukHlPUc-QzO7wpY4G2w0Wn-U',
    appId: '1:903805952685:web:e4a487ba081e0ef2109c24',
    messagingSenderId: '903805952685',
    projectId: 'oouth-e2a0e',
    authDomain: 'oouth-e2a0e.firebaseapp.com',
    storageBucket: 'oouth-e2a0e.firebasestorage.app',
    measurementId: 'G-SM6MHFHFZP',
  );

}